<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans [
        <!ELEMENT beans (context:component-scan|bean|tx:annotation-driven)*>
        <!ATTLIST beans
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xmlns:context CDATA #REQUIRED
                xmlns:aop CDATA #REQUIRED
                xmlns:tx CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT context:component-scan (#PCDATA)>
        <!ATTLIST context:component-scan
                base-package CDATA #REQUIRED>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                class CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #IMPLIED
                value CDATA #IMPLIED>
        <!ELEMENT tx:annotation-driven (#PCDATA)>
        <!ATTLIST tx:annotation-driven
                transaction-manager CDATA #REQUIRED>
        ]>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd
        http://www.springframework.org/schema/aop
        http://www.springframework.org/schema/aop/spring-aop.xsd
        http://www.springframework.org/schema/tx
        http://www.springframework.org/schema/tx/spring-tx.xsd">

<!--    开启注解扫描，管理service和dao-->
        <context:component-scan base-package="cn.lanpangtou.service"></context:component-scan>
        <context:component-scan base-package="cn.lanpangtou.mapper"></context:component-scan>

<!--    spring和mybatis整合-->
<!--    配置连接池-->
        <bean id="dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource">
            <property name="driverClass" value="com.mysql.cj.jdbc.Driver"></property>
            <property name="jdbcUrl" value="jdbc:mysql:///ordering?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC"></property>
            <property name="user" value="root"></property>
            <property name="password" value="8190972"></property>
        </bean>

<!--    配置sqlsessionfactory工厂-->
        <bean id="sessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
<!--         注入数据源-->
            <property name="dataSource" ref="dataSource"></property>

        </bean>

<!--    配置dao接口所在的包-->
        <bean id="mapperScanner" class="org.mybatis.spring.mapper.MapperScannerConfigurer">
            <property name="basePackage" value="cn.lanpangtou.mapper"></property>

        </bean>

<!--    配置spring声明式事务管理-->
<!--    配置事务管理器-->
        <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
            <property name="dataSource" ref="dataSource"></property>
        </bean>

        <tx:annotation-driven transaction-manager="transactionManager"></tx:annotation-driven>
</beans>